name: ibrat_debate_scanner_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1 # Updated to the latest stable Dart SDK version corresponding to Flutter 3.32.5

dependencies:
  flutter:
    sdk: flutter

  # for design_system
  l: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

  #for locale storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  #for state management
  flutter_riverpod: ^2.6.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2 # Current stable is 0.20.2

  # for Network
  dio: ^5.4.3 # Updated from 5.4.1 to 5.4.3
  connectivity_plus: ^6.0.3

  # for utils
#  device_preview: ^1.3.1 # Keep commented out as per your original file

  flutter_svg: ^2.2.0
  package_info_plus: ^8.3.0
  meta: ^1.16.0
  auto_route: ^10.1.0+1
  persistent_bottom_nav_bar: ^6.2.1

  mobile_scanner: ^7.0.1
  url_launcher: ^6.3.1
  uuid_v4: ^1.0.2
  uuid: ^4.5.1
  mask_text_input_formatter: ^2.9.0
  dropdown_button2: ^2.3.9
  data_table_2: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0 # Updated from 5.0.0 to 6.0.0
  auto_route_generator: ^10.2.3 # Appears to be the latest, no newer stable found.
  json_serializable: ^6.9.5
  build_runner: ^2.5.4 # Appears to be the latest, no newer stable found.
  freezed: ^3.0.6


flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf


flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/l10n
  template-arb-file: intl_en.arb
  output-localization-file: app_localizations.dart
  use_deferred_loading: false